#! /bin/sh
setxkbmap -layout latam
~/.fehbg &

for mon in $(polybar --list-monitors | cut -d":" -f1); do
	(MONITOR=$mon polybar -q pam1 -c "${HOME}"/.config/bspwm/polybar) &
	(MONITOR=$mon polybar -q pam2 -c "${HOME}"/.config/bspwm/polybar) &
	(MONITOR=$mon polybar -q pam3 -c "${HOME}"/.config/bspwm/polybar) &
	(MONITOR=$mon polybar -q pam4 -c "${HOME}"/.config/bspwm/polybar) &
done
pgrep sxhkd   || (sxhkd -c $HOME/.config/bspwm/sxhkdrc &)
dunst &
bspc monitor -d 1 2 3 4 5 6 7 8 9 10
xsetroot -cursor_name left_ptr &

#bspc config border_width         3
#bspc config normal_border_color   "#3b4252"
# bspc config normal_border_color   "#2e3440"
bspc config focused_border_color  "#008f11"
#bspc config presel_feedback_color "#88c0d0"
#bspc config window_gap           0
#bspc config focus_follows_pointer true

#bspc config split_ratio          0.52
#bspc config borderless_monocle   true
#bspc config gapless_monocle      true
#bspc config single_monocle       true

bspc config window_gap                5
bspc config split_ratio               0.53
bspc config single_monocle            true

bspc config automatic_scheme          longest_side
bspc config initial_polarity          second_child
bspc config removal_adjustment        true

bspc config focus_follows_pointer     true
bspc config pointer_follows_focus     false
bspc config pointer_follows_monitor   true
bspc config pointer_motion_interval   7
bspc config pointer_modifier          mod4
bspc config pointer_action1           move
bspc config pointer_action2           resize_side
bspc config pointer_action3           resize_corner

bspc rule -a FloaTerm state=floating center=on rectangle=700x500+0+0 
